package com.qushop.common.sms.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "LinkWSSoap", targetNamespace = "http://tempuri.org/")
public interface LinkWSSoap {

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
	@WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.HelloWorld")
	@ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.HelloWorldResponse")
	public String helloWorld();

	/**
	 * 
	 * @param content
	 * @param pwd
	 * @param cell
	 * @param sendTime
	 * @param corpID
	 * @param mobile
	 * @return returns int
	 */
	@WebMethod(operationName = "BatchSend", action = "http://tempuri.org/BatchSend")
	@WebResult(name = "BatchSendResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "BatchSend", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.BatchSend")
	@ResponseWrapper(localName = "BatchSendResponse", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.BatchSendResponse")
	public int batchSend(
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/") String pwd,
			@WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/") String mobile,
			@WebParam(name = "Content", targetNamespace = "http://tempuri.org/") String content,
			@WebParam(name = "Cell", targetNamespace = "http://tempuri.org/") String cell,
			@WebParam(name = "SendTime", targetNamespace = "http://tempuri.org/") String sendTime);

	/**
	 * 
	 * @param pwd
	 * @param cell
	 * @param corpID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetReportFail", action = "http://tempuri.org/GetReportFail")
	@WebResult(name = "GetReportFailResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetReportFail", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.GetReportFail")
	@ResponseWrapper(localName = "GetReportFailResponse", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.GetReportFailResponse")
	public String getReportFail(
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/") String pwd,
			@WebParam(name = "cell", targetNamespace = "http://tempuri.org/") String cell);

	/**
	 * 
	 * @param corpName
	 * @param pwd
	 * @param memo
	 * @param email
	 * @param linkMan
	 * @param tel
	 * @param corpID
	 * @param mobile
	 * @return returns int
	 */
	@WebMethod(operationName = "Reg", action = "http://tempuri.org/Reg")
	@WebResult(name = "RegResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "Reg", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.Reg")
	@ResponseWrapper(localName = "RegResponse", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.RegResponse")
	public int reg(
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/") String pwd,
			@WebParam(name = "CorpName", targetNamespace = "http://tempuri.org/") String corpName,
			@WebParam(name = "LinkMan", targetNamespace = "http://tempuri.org/") String linkMan,
			@WebParam(name = "Tel", targetNamespace = "http://tempuri.org/") String tel,
			@WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/") String mobile,
			@WebParam(name = "Email", targetNamespace = "http://tempuri.org/") String email,
			@WebParam(name = "Memo", targetNamespace = "http://tempuri.org/") String memo);

	/**
	 * 
	 * @param newPwd
	 * @param pwd
	 * @param corpID
	 * @return returns int
	 */
	@WebMethod(operationName = "UpdPwd", action = "http://tempuri.org/UpdPwd")
	@WebResult(name = "UpdPwdResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "UpdPwd", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.UpdPwd")
	@ResponseWrapper(localName = "UpdPwdResponse", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.UpdPwdResponse")
	public int updPwd(
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/") String pwd,
			@WebParam(name = "NewPwd", targetNamespace = "http://tempuri.org/") String newPwd);

	/**
	 * 
	 * @param corpName
	 * @param pwd
	 * @param memo
	 * @param email
	 * @param linkMan
	 * @param tel
	 * @param corpID
	 * @param mobile
	 * @return returns int
	 */
	@WebMethod(operationName = "UpdReg", action = "http://tempuri.org/UpdReg")
	@WebResult(name = "UpdRegResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "UpdReg", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.UpdReg")
	@ResponseWrapper(localName = "UpdRegResponse", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.UpdRegResponse")
	public int updReg(
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/") String pwd,
			@WebParam(name = "CorpName", targetNamespace = "http://tempuri.org/") String corpName,
			@WebParam(name = "LinkMan", targetNamespace = "http://tempuri.org/") String linkMan,
			@WebParam(name = "Tel", targetNamespace = "http://tempuri.org/") String tel,
			@WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/") String mobile,
			@WebParam(name = "Email", targetNamespace = "http://tempuri.org/") String email,
			@WebParam(name = "Memo", targetNamespace = "http://tempuri.org/") String memo);

	/**
	 * 
	 * @param pwd
	 * @param corpID
	 * @return returns int
	 */
	@WebMethod(operationName = "SelSum", action = "http://tempuri.org/SelSum")
	@WebResult(name = "SelSumResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SelSum", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.SelSum")
	@ResponseWrapper(localName = "SelSumResponse", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.SelSumResponse")
	public int selSum(
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/") String pwd);

	/**
	 * 
	 * @param content
	 * @param pwd
	 * @param cell
	 * @param sendTime
	 * @param corpID
	 * @param mobile
	 * @return returns int
	 */
	@WebMethod(operationName = "Send", action = "http://tempuri.org/Send")
	@WebResult(name = "SendResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "Send", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.Send")
	@ResponseWrapper(localName = "SendResponse", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.SendResponse")
	public int send(
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/") String pwd,
			@WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/") String mobile,
			@WebParam(name = "Content", targetNamespace = "http://tempuri.org/") String content,
			@WebParam(name = "Cell", targetNamespace = "http://tempuri.org/") String cell,
			@WebParam(name = "SendTime", targetNamespace = "http://tempuri.org/") String sendTime);

	/**
	 * 
	 * @param pwd
	 * @param corpID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Get", action = "http://tempuri.org/Get")
	@WebResult(name = "GetResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "Get", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.Get")
	@ResponseWrapper(localName = "GetResponse", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.GetResponse")
	public String get(
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/") String pwd);

	/**
	 * 
	 * @param pwd
	 * @param corpID
	 * @return returns int
	 */
	@WebMethod(operationName = "UnReg", action = "http://tempuri.org/UnReg")
	@WebResult(name = "UnRegResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "UnReg", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.UnReg")
	@ResponseWrapper(localName = "UnRegResponse", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.UnRegResponse")
	public int unReg(
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/") String pwd);

	/**
	 * 
	 * @param cardNo
	 * @param cardPwd
	 * @param pwd
	 * @param corpID
	 * @return returns int
	 */
	@WebMethod(operationName = "ChargeUp", action = "http://tempuri.org/ChargeUp")
	@WebResult(name = "ChargeUpResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "ChargeUp", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.ChargeUp")
	@ResponseWrapper(localName = "ChargeUpResponse", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.ChargeUpResponse")
	public int chargeUp(
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/") String pwd,
			@WebParam(name = "CardNo", targetNamespace = "http://tempuri.org/") String cardNo,
			@WebParam(name = "CardPwd", targetNamespace = "http://tempuri.org/") String cardPwd);

	/**
	 * 
	 * @param mmsBalance
	 * @param smsBalance
	 * @param corpID
	 * @param loginPwd
	 * @param loginName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AgentChangeAccount", action = "http://tempuri.org/AgentChangeAccount")
	@WebResult(name = "AgentChangeAccountResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "AgentChangeAccount", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.AgentChangeAccount")
	@ResponseWrapper(localName = "AgentChangeAccountResponse", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.AgentChangeAccountResponse")
	public String agentChangeAccount(
			@WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/") String loginName,
			@WebParam(name = "LoginPwd", targetNamespace = "http://tempuri.org/") String loginPwd,
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "SmsBalance", targetNamespace = "http://tempuri.org/") int smsBalance,
			@WebParam(name = "MmsBalance", targetNamespace = "http://tempuri.org/") int mmsBalance);

	/**
	 * 
	 * @param pwd
	 * @param corpID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "BalanceMMS", action = "http://tempuri.org/BalanceMMS")
	@WebResult(name = "BalanceMMSResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "BalanceMMS", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.BalanceMMS")
	@ResponseWrapper(localName = "BalanceMMSResponse", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.BalanceMMSResponse")
	public String balanceMMS(
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/") String pwd);

	/**
	 * 
	 * @param title
	 * @param pwd
	 * @param extCode
	 * @param sendTime
	 * @param corpID
	 * @param base64Content
	 * @param mobile
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SendMMS", action = "http://tempuri.org/SendMMS")
	@WebResult(name = "SendMMSResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SendMMS", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.SendMMS")
	@ResponseWrapper(localName = "SendMMSResponse", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.SendMMSResponse")
	public String sendMMS(
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/") String pwd,
			@WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/") String mobile,
			@WebParam(name = "Base64Content", targetNamespace = "http://tempuri.org/") String base64Content,
			@WebParam(name = "Title", targetNamespace = "http://tempuri.org/") String title,
			@WebParam(name = "ExtCode", targetNamespace = "http://tempuri.org/") String extCode,
			@WebParam(name = "SendTime", targetNamespace = "http://tempuri.org/") String sendTime);

	/**
	 * 
	 * @param title
	 * @param pwd
	 * @param extCode
	 * @param mobiles
	 * @param sendTime
	 * @param corpID
	 * @param base64Content
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "BatchSendMMS", action = "http://tempuri.org/BatchSendMMS")
	@WebResult(name = "BatchSendMMSResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "BatchSendMMS", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.BatchSendMMS")
	@ResponseWrapper(localName = "BatchSendMMSResponse", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.BatchSendMMSResponse")
	public String batchSendMMS(
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/") String pwd,
			@WebParam(name = "Mobiles", targetNamespace = "http://tempuri.org/") String mobiles,
			@WebParam(name = "Base64Content", targetNamespace = "http://tempuri.org/") String base64Content,
			@WebParam(name = "Title", targetNamespace = "http://tempuri.org/") String title,
			@WebParam(name = "ExtCode", targetNamespace = "http://tempuri.org/") String extCode,
			@WebParam(name = "SendTime", targetNamespace = "http://tempuri.org/") String sendTime);

	/**
	 * 
	 * @param pwd
	 * @param cell
	 * @param corpID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetReportFailMMS", action = "http://tempuri.org/GetReportFailMMS")
	@WebResult(name = "GetReportFailMMSResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetReportFailMMS", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.GetReportFailMMS")
	@ResponseWrapper(localName = "GetReportFailMMSResponse", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.GetReportFailMMSResponse")
	public String getReportFailMMS(
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/") String pwd,
			@WebParam(name = "cell", targetNamespace = "http://tempuri.org/") String cell);

	/**
	 * 
	 * @param pwd
	 * @param corpID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetMMS", action = "http://tempuri.org/GetMMS")
	@WebResult(name = "GetMMSResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetMMS", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.GetMMS")
	@ResponseWrapper(localName = "GetMMSResponse", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.GetMMSResponse")
	public String getMMS(
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/") String pwd);

	/**
	 * 
	 * @param cardNo
	 * @param cardPwd
	 * @param pwd
	 * @param corpID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ChargeUpMMS", action = "http://tempuri.org/ChargeUpMMS")
	@WebResult(name = "ChargeUpMMSResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "ChargeUpMMS", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.ChargeUpMMS")
	@ResponseWrapper(localName = "ChargeUpMMSResponse", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.ChargeUpMMSResponse")
	public String chargeUpMMS(
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/") String pwd,
			@WebParam(name = "CardNo", targetNamespace = "http://tempuri.org/") String cardNo,
			@WebParam(name = "CardPwd", targetNamespace = "http://tempuri.org/") String cardPwd);

	/**
	 * 
	 * @param corpName
	 * @param memo
	 * @param email
	 * @param linkMan
	 * @param tel
	 * @param corpID
	 * @param loginPwd
	 * @param pass
	 * @param mobile
	 * @param loginName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AgentMakeAccount", action = "http://tempuri.org/AgentMakeAccount")
	@WebResult(name = "AgentMakeAccountResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "AgentMakeAccount", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.AgentMakeAccount")
	@ResponseWrapper(localName = "AgentMakeAccountResponse", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.AgentMakeAccountResponse")
	public String agentMakeAccount(
			@WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/") String loginName,
			@WebParam(name = "LoginPwd", targetNamespace = "http://tempuri.org/") String loginPwd,
			@WebParam(name = "CorpName", targetNamespace = "http://tempuri.org/") String corpName,
			@WebParam(name = "LinkMan", targetNamespace = "http://tempuri.org/") String linkMan,
			@WebParam(name = "Tel", targetNamespace = "http://tempuri.org/") String tel,
			@WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/") String mobile,
			@WebParam(name = "Email", targetNamespace = "http://tempuri.org/") String email,
			@WebParam(name = "Memo", targetNamespace = "http://tempuri.org/") String memo,
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "Pass", targetNamespace = "http://tempuri.org/") String pass);

	/**
	 * 
	 * @param pwd
	 * @param corpID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetReportSMS", action = "http://tempuri.org/GetReportSMS")
	@WebResult(name = "GetReportSMSResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetReportSMS", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.GetReportSMS")
	@ResponseWrapper(localName = "GetReportSMSResponse", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.GetReportSMSResponse")
	public String getReportSMS(
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/") String pwd);

	/**
	 * 
	 * @param pwd
	 * @param corpID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetReportMMS", action = "http://tempuri.org/GetReportMMS")
	@WebResult(name = "GetReportMMSResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetReportMMS", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.GetReportMMS")
	@ResponseWrapper(localName = "GetReportMMSResponse", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.GetReportMMSResponse")
	public String getReportMMS(
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/") String pwd);

	/**
	 * 
	 * @param content
	 * @param pwd
	 * @param cell
	 * @param sendTime
	 * @param corpID
	 * @param mobile
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Send2", action = "http://tempuri.org/Send2")
	@WebResult(name = "Send2Result", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "Send2", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.Send2")
	@ResponseWrapper(localName = "Send2Response", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.Send2Response")
	public String send2(
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/") String pwd,
			@WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/") String mobile,
			@WebParam(name = "Content", targetNamespace = "http://tempuri.org/") String content,
			@WebParam(name = "Cell", targetNamespace = "http://tempuri.org/") String cell,
			@WebParam(name = "SendTime", targetNamespace = "http://tempuri.org/") String sendTime);

	/**
	 * 
	 * @param title
	 * @param pwd
	 * @param extCode
	 * @param sendTime
	 * @param corpID
	 * @param base64Content
	 * @param mobile
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SendMMS2", action = "http://tempuri.org/SendMMS2")
	@WebResult(name = "SendMMS2Result", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SendMMS2", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.SendMMS2")
	@ResponseWrapper(localName = "SendMMS2Response", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.SendMMS2Response")
	public String sendMMS2(
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/") String pwd,
			@WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/") String mobile,
			@WebParam(name = "Base64Content", targetNamespace = "http://tempuri.org/") String base64Content,
			@WebParam(name = "Title", targetNamespace = "http://tempuri.org/") String title,
			@WebParam(name = "ExtCode", targetNamespace = "http://tempuri.org/") String extCode,
			@WebParam(name = "SendTime", targetNamespace = "http://tempuri.org/") String sendTime);

	/**
	 * 
	 * @param content
	 * @param pwd
	 * @param cell
	 * @param sendTime
	 * @param corpID
	 * @param mobile
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "BatchSend2", action = "http://tempuri.org/BatchSend2")
	@WebResult(name = "BatchSend2Result", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "BatchSend2", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.BatchSend2")
	@ResponseWrapper(localName = "BatchSend2Response", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.BatchSend2Response")
	public String batchSend2(
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/") String pwd,
			@WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/") String mobile,
			@WebParam(name = "Content", targetNamespace = "http://tempuri.org/") String content,
			@WebParam(name = "Cell", targetNamespace = "http://tempuri.org/") String cell,
			@WebParam(name = "SendTime", targetNamespace = "http://tempuri.org/") String sendTime);

	/**
	 * 
	 * @param title
	 * @param pwd
	 * @param extCode
	 * @param mobiles
	 * @param sendTime
	 * @param corpID
	 * @param base64Content
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "BatchSendMMS2", action = "http://tempuri.org/BatchSendMMS2")
	@WebResult(name = "BatchSendMMS2Result", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "BatchSendMMS2", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.BatchSendMMS2")
	@ResponseWrapper(localName = "BatchSendMMS2Response", targetNamespace = "http://tempuri.org/", className = "com.qushop.common.sms.webservice.BatchSendMMS2Response")
	public String batchSendMMS2(
			@WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/") String corpID,
			@WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/") String pwd,
			@WebParam(name = "Mobiles", targetNamespace = "http://tempuri.org/") String mobiles,
			@WebParam(name = "Base64Content", targetNamespace = "http://tempuri.org/") String base64Content,
			@WebParam(name = "Title", targetNamespace = "http://tempuri.org/") String title,
			@WebParam(name = "ExtCode", targetNamespace = "http://tempuri.org/") String extCode,
			@WebParam(name = "SendTime", targetNamespace = "http://tempuri.org/") String sendTime);

}
