package com.qushop.common.sms.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "LinkWSHttpGet", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LinkWSHttpGet {

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "HelloWorld")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String helloWorld();

	/**
	 * 
	 * @param content
	 * @param pwd
	 * @param cell
	 * @param sendTime
	 * @param corpID
	 * @param mobile
	 * @return returns int
	 */
	@WebMethod(operationName = "BatchSend")
	@WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
	public int batchSend(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd") String pwd,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobile") String mobile,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Content") String content,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Cell") String cell,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SendTime") String sendTime);

	/**
	 * 
	 * @param pwd
	 * @param cell
	 * @param corpID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetReportFail")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getReportFail(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd") String pwd,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "cell") String cell);

	/**
	 * 
	 * @param corpName
	 * @param pwd
	 * @param memo
	 * @param email
	 * @param linkMan
	 * @param tel
	 * @param corpID
	 * @param mobile
	 * @return returns int
	 */
	@WebMethod(operationName = "Reg")
	@WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
	public int reg(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd") String pwd,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpName") String corpName,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "LinkMan") String linkMan,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Tel") String tel,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobile") String mobile,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Email") String email,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Memo") String memo);

	/**
	 * 
	 * @param newPwd
	 * @param pwd
	 * @param corpID
	 * @return returns int
	 */
	@WebMethod(operationName = "UpdPwd")
	@WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
	public int updPwd(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd") String pwd,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "NewPwd") String newPwd);

	/**
	 * 
	 * @param corpName
	 * @param pwd
	 * @param memo
	 * @param email
	 * @param linkMan
	 * @param tel
	 * @param corpID
	 * @param mobile
	 * @return returns int
	 */
	@WebMethod(operationName = "UpdReg")
	@WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
	public int updReg(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd") String pwd,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpName") String corpName,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "LinkMan") String linkMan,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Tel") String tel,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobile") String mobile,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Email") String email,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Memo") String memo);

	/**
	 * 
	 * @param pwd
	 * @param corpID
	 * @return returns int
	 */
	@WebMethod(operationName = "SelSum")
	@WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
	public int selSum(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd") String pwd);

	/**
	 * 
	 * @param content
	 * @param pwd
	 * @param cell
	 * @param sendTime
	 * @param corpID
	 * @param mobile
	 * @return returns int
	 */
	@WebMethod(operationName = "Send")
	@WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
	public int send(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd") String pwd,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobile") String mobile,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Content") String content,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Cell") String cell,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SendTime") String sendTime);

	/**
	 * 
	 * @param pwd
	 * @param corpID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Get")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String get(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd") String pwd);

	/**
	 * 
	 * @param pwd
	 * @param corpID
	 * @return returns int
	 */
	@WebMethod(operationName = "UnReg")
	@WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
	public int unReg(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd") String pwd);

	/**
	 * 
	 * @param cardNo
	 * @param cardPwd
	 * @param pwd
	 * @param corpID
	 * @return returns int
	 */
	@WebMethod(operationName = "ChargeUp")
	@WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
	public int chargeUp(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd") String pwd,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CardNo") String cardNo,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CardPwd") String cardPwd);

	/**
	 * 
	 * @param mmsBalance
	 * @param smsBalance
	 * @param corpID
	 * @param loginPwd
	 * @param loginName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AgentChangeAccount")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String agentChangeAccount(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "LoginName") String loginName,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "LoginPwd") String loginPwd,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SmsBalance") String smsBalance,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "MmsBalance") String mmsBalance);

	/**
	 * 
	 * @param pwd
	 * @param corpID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "BalanceMMS")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String balanceMMS(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd") String pwd);

	/**
	 * 
	 * @param title
	 * @param pwd
	 * @param extCode
	 * @param sendTime
	 * @param corpID
	 * @param base64Content
	 * @param mobile
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SendMMS")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String sendMMS(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd") String pwd,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobile") String mobile,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Base64Content") String base64Content,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Title") String title,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ExtCode") String extCode,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SendTime") String sendTime);

	/**
	 * 
	 * @param title
	 * @param pwd
	 * @param extCode
	 * @param mobiles
	 * @param sendTime
	 * @param corpID
	 * @param base64Content
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "BatchSendMMS")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String batchSendMMS(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd") String pwd,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobiles") String mobiles,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Base64Content") String base64Content,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Title") String title,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ExtCode") String extCode,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SendTime") String sendTime);

	/**
	 * 
	 * @param pwd
	 * @param cell
	 * @param corpID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetReportFailMMS")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getReportFailMMS(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd") String pwd,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "cell") String cell);

	/**
	 * 
	 * @param pwd
	 * @param corpID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetMMS")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getMMS(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd") String pwd);

	/**
	 * 
	 * @param cardNo
	 * @param cardPwd
	 * @param pwd
	 * @param corpID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ChargeUpMMS")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String chargeUpMMS(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd") String pwd,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CardNo") String cardNo,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CardPwd") String cardPwd);

	/**
	 * 
	 * @param corpName
	 * @param memo
	 * @param email
	 * @param linkMan
	 * @param tel
	 * @param corpID
	 * @param loginPwd
	 * @param pass
	 * @param mobile
	 * @param loginName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AgentMakeAccount")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String agentMakeAccount(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "LoginName") String loginName,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "LoginPwd") String loginPwd,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpName") String corpName,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "LinkMan") String linkMan,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Tel") String tel,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobile") String mobile,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Email") String email,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Memo") String memo,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pass") String pass);

	/**
	 * 
	 * @param pwd
	 * @param corpID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetReportSMS")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getReportSMS(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd") String pwd);

	/**
	 * 
	 * @param pwd
	 * @param corpID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetReportMMS")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getReportMMS(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd") String pwd);

	/**
	 * 
	 * @param content
	 * @param pwd
	 * @param cell
	 * @param sendTime
	 * @param corpID
	 * @param mobile
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Send2")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String send2(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd") String pwd,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobile") String mobile,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Content") String content,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Cell") String cell,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SendTime") String sendTime);

	/**
	 * 
	 * @param title
	 * @param pwd
	 * @param extCode
	 * @param sendTime
	 * @param corpID
	 * @param base64Content
	 * @param mobile
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SendMMS2")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String sendMMS2(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd") String pwd,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobile") String mobile,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Base64Content") String base64Content,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Title") String title,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ExtCode") String extCode,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SendTime") String sendTime);

	/**
	 * 
	 * @param content
	 * @param pwd
	 * @param cell
	 * @param sendTime
	 * @param corpID
	 * @param mobile
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "BatchSend2")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String batchSend2(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd") String pwd,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobile") String mobile,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Content") String content,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Cell") String cell,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SendTime") String sendTime);

	/**
	 * 
	 * @param title
	 * @param pwd
	 * @param extCode
	 * @param mobiles
	 * @param sendTime
	 * @param corpID
	 * @param base64Content
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "BatchSendMMS2")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String batchSendMMS2(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CorpID") String corpID,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Pwd") String pwd,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Mobiles") String mobiles,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Base64Content") String base64Content,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Title") String title,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ExtCode") String extCode,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SendTime") String sendTime);

}
