package com.qushop.common.sms.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * LinkWS service = new LinkWS();
 * LinkWSSoap portType = service.getLinkWSSoap();
 * portType.helloWorld(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "LinkWS", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://mb345.com:999/ws/LinkWS.asmx?wsdl")
public class LinkWS extends Service {

	private final static URL LINKWS_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.qushop.common.sms.webservice.LinkWS.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.qushop.common.sms.webservice.LinkWS.class
					.getResource(".");
			url = new URL(baseUrl, "http://mb345.com:999/ws/LinkWS.asmx?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://mb345.com:999/ws/LinkWS.asmx?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		LINKWS_WSDL_LOCATION = url;
	}

	public LinkWS(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public LinkWS() {
		super(LINKWS_WSDL_LOCATION, new QName("http://tempuri.org/", "LinkWS"));
	}

	/**
	 * 
	 * @return returns LinkWSSoap
	 */
	@WebEndpoint(name = "LinkWSSoap")
	public LinkWSSoap getLinkWSSoap() {
		return super.getPort(new QName("http://tempuri.org/", "LinkWSSoap"),
				LinkWSSoap.class);
	}

	/**
	 * 
	 * @return returns LinkWSSoap
	 */
	@WebEndpoint(name = "LinkWSSoap12")
	public LinkWSSoap getLinkWSSoap12() {
		return super.getPort(new QName("http://tempuri.org/", "LinkWSSoap12"),
				LinkWSSoap.class);
	}

	/**
	 * 
	 * @return returns LinkWSHttpGet
	 */
	@WebEndpoint(name = "LinkWSHttpGet")
	public LinkWSHttpGet getLinkWSHttpGet() {
		return super.getPort(new QName("http://tempuri.org/", "LinkWSHttpGet"),
				LinkWSHttpGet.class);
	}

	/**
	 * 
	 * @return returns LinkWSHttpPost
	 */
	@WebEndpoint(name = "LinkWSHttpPost")
	public LinkWSHttpPost getLinkWSHttpPost() {
		return super.getPort(
				new QName("http://tempuri.org/", "LinkWSHttpPost"),
				LinkWSHttpPost.class);
	}

}
